/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinal;

import JavaBeans.Boletim;
import classesDao.BoletimDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Note
 */
public class AlteraBoletim extends javax.swing.JPanel {

    /**
     * Creates new form AlteraBoletim
     */
    public AlteraBoletim() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTBoletim.getModel();
        jTBoletim.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
    
      public void limpajTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTBoletim.getModel();
        while (jTBoletim.getModel().getRowCount() > 0)
            modelo.removeRow(0);
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTBoletim.getModel();
        
        BoletimDao boleDao = new BoletimDao();
        
        for(Boletim bole: boleDao.read2()){
            modelo.addRow(new Object[]{
                bole.getIdBoletim(),
                bole.getMedia(),
                bole.getFalta(),
                bole.getNomeAluno(),
                bole.getMateria()
            });    

        }
    }
    
    public void selecionaLinha(){ //Seleciona a linha da tabela
         if(jTBoletim.getSelectedRow() != -1){ 
            media.setText(jTBoletim.getValueAt(jTBoletim.getSelectedRow(), 1).toString()); 
            faltas.setText(jTBoletim.getValueAt(jTBoletim.getSelectedRow(), 2).toString());
       }
       else{
           JOptionPane.showMessageDialog(null,"Selecione uma linha");
       }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faltas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        media = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBoletim = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setText("Média");

        jLabel4.setText("faltas");

        jTBoletim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id boletim", "Média", "Faltas", "Aluno", "Materia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBoletim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBoletimMouseClicked(evt);
            }
        });
        jTBoletim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBoletimKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTBoletim);

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(faltas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(media, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(568, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addGap(11, 11, 11)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(faltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(160, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTBoletimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBoletimMouseClicked
        selecionaLinha();
    }//GEN-LAST:event_jTBoletimMouseClicked

    private void jTBoletimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBoletimKeyReleased
        selecionaLinha();
    }//GEN-LAST:event_jTBoletimKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        BoletimDao bd = new BoletimDao();
        Boletim bole = new Boletim();

        if(jTBoletim.getSelectedRow() != -1){
            bole.setIdBoletim(Integer.parseInt(jTBoletim.getValueAt(jTBoletim.getSelectedRow(), 0).toString()));
            bole.setFalta(Integer.parseInt(faltas.getText()));
            bole.setMedia(Float.parseFloat(media.getText()));
            
            bd.update(bole);
            limpajTable();
            readJTable();

            faltas.setText("");
            media.setText("");
            
        }else{
            JOptionPane.showMessageDialog(null,"Selecione uma linha");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BoletimDao bd = new BoletimDao();
        Boletim bole = new Boletim();
        
        bole.setIdBoletim(Integer.parseInt(jTBoletim.getValueAt(jTBoletim.getSelectedRow(), 0).toString()));
        
            
        bd.delete(bole);
        limpajTable();
        readJTable();

        faltas.setText("");
        media.setText("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField faltas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBoletim;
    private javax.swing.JTextField media;
    // End of variables declaration//GEN-END:variables
}
