/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinal;

import JavaBeans.Campus;
import JavaBeans.Estado;
import JavaBeans.Professor;
import classesDao.CampusDao;
import classesDao.EstadoDao;
import classesDao.ProfessorDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Note
 */
public class AlteraDadosProf extends javax.swing.JPanel {

    /**
     * Creates new form AlteraDadosProf
     */
    EstadoDao estDao = new EstadoDao();
    CampusDao cDao = new CampusDao();
    public AlteraDadosProf() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) jTProfessor.getModel();
        jTProfessor.setRowSorter(new TableRowSorter(modelo));
        readJTable();
        
         ///////////////////////COMBO BOX ESTADO
        for(Estado estad: estDao.read()){
            this.estado.addItem(estad);
        }
        
        ///////////////////////COMBO BOX CAMPUS
        for(Campus cam : cDao.read()){
            this.campus.addItem(cam);
        }
    }
    
     public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTProfessor.getModel();
        
        ProfessorDao profDao = new ProfessorDao();
        
        for(Professor pro: profDao.read()){
            modelo.addRow(new Object[]{
                pro.getId(),
                pro.getNome(),
                pro.getEmail(),
                pro.getCpf(),
                pro.getRg(),
                pro.getEstado(),
                pro.getCampus(),
                pro.getCidade(),
                pro.getRua(),
                pro.getNumCasa(),
                pro.getTelefone()
            });    

        }
    }
    
     public void limpajTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTProfessor.getModel();
        while (jTProfessor.getModel().getRowCount() > 0)
            modelo.removeRow(0);
    }
    
    public void selecionaLinha(){ //Seleciona a linha da tabela
         if(jTProfessor.getSelectedRow() != -1){ 
            nome.setText(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 1).toString()); 
            
            
            email.setText(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 2).toString()); 
            cpf.setText(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 3).toString()); 
            rg.setText(jTProfessor.getValueAt(jTProfessor.getSelectedRow(),4).toString());

            for(Estado est: new EstadoDao().read())
                if(est.getUf().equals(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 5).toString())){
                    estado.getModel().setSelectedItem(est);
                }

            for(Campus camp: new CampusDao().read()){
                if(camp.getNome().equals(jTProfessor.getValueAt(jTProfessor.getSelectedRow(),6).toString())){
                    campus.getModel().setSelectedItem(camp);
                }
            }
            

            cidade.setText(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 7).toString());
            rua.setText(jTProfessor.getValueAt(jTProfessor.getSelectedRow(),8).toString());
            numCasa.setText(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 9).toString());
            telefone.setText(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 10).toString());
       }
       else{
           JOptionPane.showMessageDialog(null,"Selecione uma linha");
       }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        rua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numCasa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProfessor = new javax.swing.JTable();

        jLabel3.setText("Campus");

        jLabel4.setText("Estado");

        jLabel5.setText("Email");

        jLabel6.setText("CPF");

        jLabel7.setText("Rg");

        jLabel8.setText("Cidade");

        jLabel9.setText("Rua");

        jLabel10.setText("N°");

        jLabel11.setText("Telefone");

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "CPF", "Rg", "UF", "Campus", "Cidade", "Rua", "N°", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProfessorMouseClicked(evt);
            }
        });
        jTProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTProfessorKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTProfessor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(116, 116, 116))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Campus camp = (Campus) campus.getSelectedItem();//faz um cast de acordo com o item selecionado
        Estado estad = (Estado) estado.getSelectedItem();
        
        ProfessorDao pd = new ProfessorDao();
        Professor prof = new Professor();

        if(jTProfessor.getSelectedRow() != -1){
            prof.setId(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 0).toString());
            prof.setNome(nome.getText());
            prof.setCpf(cpf.getText());
            prof.setRg(rg.getText());
            prof.setRua(rua.getText());
            prof.setCidade(cidade.getText());
            prof.setNumCasa(numCasa.getText());
            prof.setTelefone(telefone.getText());
            prof.setEmail(email.getText());
            prof.setIdCampus(camp.getIdCampus());
            prof.setIdEstado(estad.getId());
            

            pd.update(prof);
            limpajTable();
            readJTable();

            nome.setText("");
            cpf.setText("");
            rg.setText("");
            rua.setText("");
            cidade.setText("");
            numCasa.setText("");
            telefone.setText("");
            email.setText("");
        }else{
            JOptionPane.showMessageDialog(null,"Selecione uma linha");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Professor prof = new Professor();
        ProfessorDao pd = new ProfessorDao();
        prof.setId(jTProfessor.getValueAt(jTProfessor.getSelectedRow(), 0).toString());
        pd.delete(prof);
        limpajTable();
        readJTable();

        nome.setText("");
        cpf.setText("");
        rg.setText("");
        rua.setText("");
        cidade.setText("");
        numCasa.setText("");
        telefone.setText("");
        email.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProfessorMouseClicked
        selecionaLinha();
    }//GEN-LAST:event_jTProfessorMouseClicked

    private void jTProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProfessorKeyReleased
        selecionaLinha();
    }//GEN-LAST:event_jTProfessorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> campus;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<Object> estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProfessor;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numCasa;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables
}
