/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinal;

import JavaBeans.Alunos;
import JavaBeans.Campus;
import JavaBeans.Curso;
import JavaBeans.Estado;
import classesDao.AlunoDao;
import classesDao.CampusDao;
import classesDao.CursoDao;
import classesDao.EstadoDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Note
 */
public class AlteraDadosAlun extends javax.swing.JPanel {

    /**
     * Creates new form AlteraDadosAlun
     */
    CursoDao cursDao = new CursoDao();
    EstadoDao estDao = new EstadoDao();
    CampusDao cDao = new CampusDao();
    public AlteraDadosAlun() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) jTAluno.getModel();
        jTAluno.setRowSorter(new TableRowSorter(modelo));
        readJTable();
        
         ///////////////////////COMBO BOX CURSO
        for(Curso c: cursDao.read()){
            this.curso.addItem(c);
        }
        
        ///////////////////////COMBO BOX ESTADO
        for(Estado estad: estDao.read()){
            this.estado.addItem(estad);
        }
        
        ///////////////////////COMBO BOX CAMPUS
        for(Campus cam : cDao.read()){
            this.campus.addItem(cam);
        }

    }
    public void limpajTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTAluno.getModel();
        while (jTAluno.getModel().getRowCount() > 0)
            modelo.removeRow(0);
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTAluno.getModel();
        
        AlunoDao aluDao = new AlunoDao();
        
        for(Alunos alu: aluDao.read()){
            modelo.addRow(new Object[]{
                alu.getId(),
                alu.getNome(),
                alu.getCurso(),
                alu.getEmail(),
                alu.getCpf(),
                alu.getRg(),
                alu.getEstado(),
                alu.getCampus(),
                alu.getCidade(),
                alu.getRua(),
                alu.getNumCasa(),
                alu.getTelefone()
            });    

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAluno = new javax.swing.JTable();
        nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        curso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        campus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        rua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numCasa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Curso", "Email", "CPF", "Rg", "UF", "Campus", "Cidade", "Rua", "N°", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAlunoMouseClicked(evt);
            }
        });
        jTAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTAlunoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTAluno);

        jLabel1.setText("Nome");

        curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoActionPerformed(evt);
            }
        });

        jLabel2.setText("Curso");

        jLabel3.setText("Campus");

        jLabel4.setText("Estado");

        jLabel5.setText("Email");

        jLabel6.setText("CPF");

        jLabel7.setText("Rg");

        jLabel8.setText("Cidade");

        jLabel9.setText("Rua");

        jLabel10.setText("N°");

        jLabel11.setText("Telefone");

        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(37, 37, 37)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(numCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       Campus camp = (Campus) campus.getSelectedItem();//faz um cast de acordo com o item selecionado
       Estado estad = (Estado) estado.getSelectedItem();
       Curso curs = (Curso) curso.getSelectedItem();
        AlunoDao ad = new AlunoDao();
        Alunos alu = new Alunos();
        
        if(jTAluno.getSelectedRow() != -1){
            alu.setId(jTAluno.getValueAt(jTAluno.getSelectedRow(), 0).toString());
            alu.setNome(nome.getText());
            alu.setCpf(cpf.getText());
            alu.setRg(rg.getText());
            alu.setRua(rua.getText());
            alu.setCidade(cidade.getText());
            alu.setNumCasa(numCasa.getText());
            alu.setTelefone(telefone.getText());
            alu.setEmail(email.getText());
            alu.setIdCampus(camp.getIdCampus());
            alu.setIdEstado(estad.getId());
            alu.setIdCurso(curs.getId());

            ad.update(alu);
            limpajTable();
            readJTable();
            
            nome.setText("");
            cpf.setText("");
            rg.setText("");
            rua.setText("");
            cidade.setText("");
            numCasa.setText("");
            telefone.setText("");
            email.setText("");
        }else{
            JOptionPane.showMessageDialog(null,"Selecione uma linha");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Alunos alu = new Alunos();
        AlunoDao ad = new AlunoDao();
        alu.setId(jTAluno.getValueAt(jTAluno.getSelectedRow(), 0).toString());
        ad.delete(alu);
        limpajTable();
        readJTable();
        
        nome.setText("");
        cpf.setText("");
        rg.setText("");
        rua.setText("");
        cidade.setText("");
        numCasa.setText("");
        telefone.setText("");
        email.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
     public void selecionaLinha(){ //Seleciona a linha da tabela
         if(jTAluno.getSelectedRow() != -1){ 
            nome.setText(jTAluno.getValueAt(jTAluno.getSelectedRow(), 1).toString()); 
            
            for(Curso curs:new CursoDao().read()){
                if(curs.getNome().equals(jTAluno.getValueAt(jTAluno.getSelectedRow(), 2).toString())){
                    curso.getModel().setSelectedItem(curs);
                }
            }
            
            email.setText(jTAluno.getValueAt(jTAluno.getSelectedRow(), 3).toString()); 
            cpf.setText(jTAluno.getValueAt(jTAluno.getSelectedRow(), 4).toString()); 
            rg.setText(jTAluno.getValueAt(jTAluno.getSelectedRow(),5).toString());

            for(Estado est: new EstadoDao().read())
                if(est.getUf().equals(jTAluno.getValueAt(jTAluno.getSelectedRow(), 6).toString())){
                    estado.getModel().setSelectedItem(est);
                }

            for(Campus camp: new CampusDao().read()){
                if(camp.getNome().equals(jTAluno.getValueAt(jTAluno.getSelectedRow(),7).toString())){
                    campus.getModel().setSelectedItem(camp);
                }
            }
            

            cidade.setText(jTAluno.getValueAt(jTAluno.getSelectedRow(), 8).toString());
            rua.setText(jTAluno.getValueAt(jTAluno.getSelectedRow(),9).toString());
            numCasa.setText(jTAluno.getValueAt(jTAluno.getSelectedRow(), 10).toString());
            telefone.setText(jTAluno.getValueAt(jTAluno.getSelectedRow(), 11).toString());
       }
       else{
           JOptionPane.showMessageDialog(null,"Selecione uma linha");
       }
     }
    private void jTAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAlunoMouseClicked
       selecionaLinha();
    }//GEN-LAST:event_jTAlunoMouseClicked
       
    private void jTAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAlunoKeyReleased
        selecionaLinha();
    }//GEN-LAST:event_jTAlunoKeyReleased

    private void cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> campus;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cpf;
    private javax.swing.JComboBox<Object> curso;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<Object> estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAluno;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numCasa;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables
}
