/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinal;

import JavaBeans.Boletim;
import classesDao.BoletimDao;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Note
 */
public class ExibeBoletim extends javax.swing.JPanel {

    /**
     * Creates new form ExibeBoletim
     */
    public ExibeBoletim() {
        initComponents();
       /* DefaultTableModel modelo = (DefaultTableModel) jTBoletim.getModel();
        jTBoletim.setRowSorter(new TableRowSorter(modelo));
        readJTable();*/
    }
    
     /*public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTBoletim.getModel();
        
        BoletimDao boleDao = new BoletimDao();
        
        for(Boletim bole: boleDao.read()){
            modelo.addRow(new Object[]{
                bole.getNomeAluno(),
                bole.getMateria(),
                bole.getPrecesa()+"%",
                bole.getMedia()
            });    

        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTBoletim = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jTBoletim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno", "Matéria", "Presença", "Média"
            }
        ));
        jScrollPane1.setViewportView(jTBoletim);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBoletim;
    // End of variables declaration//GEN-END:variables
}
