/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinal;

import classesDao.ProfessorDao;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import JavaBeans.Professor;

/**
 *
 * @author Note
 */
public class ExibirProf extends javax.swing.JPanel {

    /**
     * Creates new form ExibirProf
     */
    
    public ExibirProf() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTProfessor.getModel();
        jTProfessor.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTProfessor.getModel();
        
        ProfessorDao profDao = new ProfessorDao();
        
        for(Professor prof: profDao.read()){
            modelo.addRow(new Object[]{
                prof.getId(),
                prof.getNome(),
                prof.getEmail(),
                prof.getCpf(),
                prof.getRg(),
                prof.getCampus(),
                prof.getEstado(),
                prof.getCidade(),
                prof.getRua(),
                prof.getNumCasa(),
                prof.getTelefone(),
                new SimpleDateFormat("dd/MM/YY").format(prof.getDataNascimento().getTime())
            });    

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTProfessor = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jTProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "CPF", "RG", "Campus", "Estado", "Cidade", "Rua", "N°", "Telefone", "Data Nascimento"
            }
        ));
        jScrollPane1.setViewportView(jTProfessor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProfessor;
    // End of variables declaration//GEN-END:variables
}
