/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinal;

import JavaBeans.Alunos;
import JavaBeans.Campus;
import JavaBeans.Curso;
import JavaBeans.Estado;
import classesDao.AlunoDao;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Note
 */
public class ExibirAluno extends javax.swing.JPanel {

    /**
     * Creates new form ExibirAluno
     */
    
    public ExibirAluno() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) jTAluno.getModel();
        jTAluno.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTAluno.getModel();
        
        AlunoDao aluDao = new AlunoDao();
        
        for(Alunos alu: aluDao.read()){
            modelo.addRow(new Object[]{
                alu.getId(),
                alu.getNome(),
                alu.getCurso(),
                alu.getEmail(),
                alu.getCpf(),
                alu.getRg(),
                alu.getEstado(),
                alu.getCampus(),
                alu.getCidade(),
                alu.getRua(),
                alu.getNumCasa(),
                alu.getTelefone(),
                new SimpleDateFormat("dd/MM/YY").format(alu.getDataNascimento().getTime())
            });    

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAluno = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jTAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Curso", "Email", "CPF", "Rg", "UF", "Campus", "Cidade", "Rua", "N°", "Telefone", "Data de Nascimento"
            }
        ));
        jScrollPane1.setViewportView(jTAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAluno;
    // End of variables declaration//GEN-END:variables
}
